// <auto-generated />
using System;
using System.Text.Json;
using LoreForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace LoreForge.Infrastructure.Migrations
{
    [DbContext(typeof(LoreForgeDbContext))]
    [Migration("20260328120358_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoreForge.Core.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("FileRef")
                        .HasColumnType("text")
                        .HasColumnName("file_ref");

                    b.Property<string>("ProgressSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("progress_snapshot");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("LoreForge.Core.Entities.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.PrimitiveCollection<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("genres");

                    b.Property<JsonDocument>("Progress")
                        .HasColumnType("jsonb")
                        .HasColumnName("progress");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("LoreForge.Core.Entities.WorldNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1024)")
                        .HasColumnName("embedding");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_world_notes");

                    b.ToTable("world_notes", (string)null);
                });

            modelBuilder.Entity("LoreForge.Core.Entities.Work", b =>
                {
                    b.OwnsOne("LoreForge.Core.Entities.WorkNotes", "Notes", b1 =>
                        {
                            b1.Property<Guid>("WorkId");

                            b1.Property<string>("Characters");

                            b1.Property<string>("Magic");

                            b1.Property<string>("PlotStructure");

                            b1.Property<string>("Themes");

                            b1.Property<string>("WhatILiked");

                            b1.Property<string>("Worldbuilding");

                            b1.HasKey("WorkId");

                            b1.ToTable("works");

                            b1
                                .ToJson("notes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkId")
                                .HasConstraintName("fk_works_works_id");
                        });

                    b.Navigation("Notes")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
